import { useState } from 'react'
import { ApiError, request } from '../../app/api'
import { Button } from '../../components/ui'

export function RepresentationGeneration({ taskId, revisionId, episode, disabled, onBusy, onSaved }: {
  taskId: string; revisionId: string; episode: boolean; disabled: boolean
  onBusy: (busy: boolean) => void; onSaved: () => void
}) {
  const [target, setTarget] = useState(episode ? 'supported' : 'practice')
  const [error, setError] = useState('')
  const generate = async () => {
    onBusy(true); setError('')
    try {
      await request(`/practice-representations/tasks/${taskId}/generate`, {
        method: 'POST', body: JSON.stringify({ expected_revision_id: revisionId, target }),
      })
      onSaved()
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Representation drafts could not be generated. Reload the saved task and try again.')
    } finally { onBusy(false) }
  }
  return <section aria-label="Generate representation drafts">
    <p>Generate source-based alternatives into a new saved draft. Review factual alignment, task equivalence and support levels before approval. Existing manual alternatives are retained.</p>
    {episode && <label>Stage for generated alternatives <select value={target} disabled={disabled} onChange={event => setTarget(event.target.value)}>
      <option value="supported">Supported work: instruction and access</option>
      <option value="transfer">Fresh application: access only</option>
    </select></label>}
    <Button disabled={disabled} onClick={() => void generate()}>Generate alternatives and save draft</Button>
    {error && <p role="alert">{error}</p>}
  </section>
}

export function RepresentationGenerationNotes({ value }: { value: Record<string, unknown> }) {
  const generated = value.representation_generation
  if (!generated || typeof generated !== 'object') return null
  return <details><summary>Generated alternatives: sources and limitations</summary>
    {Object.entries(generated).map(([stage, entry]) => {
      const record = entry as { provider?: string; model?: string; candidate?: { unavailable_modes?: Array<{ mode: string; reason: string }>; variants?: Array<{ representation_id: string; title: string; source_quotes: Array<{ source_reference: string; quote: string }> }> } }
      return <div key={stage}><h4>{stage} draft</h4><p>Generated by {record.provider} / {record.model}. Generation does not approve these alternatives.</p>
        {record.candidate?.unavailable_modes?.map(item => <p key={item.mode}>{item.mode.replace('_', ' ')}: {item.reason}</p>)}
        {record.candidate?.variants?.map(item => <details key={item.representation_id}><summary>{item.title}: source excerpts</summary>
          {item.source_quotes.map((quote, index) => <blockquote key={index}><p>{quote.quote}</p><cite>Source passage {quote.source_reference}</cite></blockquote>)}
        </details>)}
      </div>
    })}
  </details>
}
