import { expect, test } from '@playwright/test'

test('learner preferences persist and opt-out restores baseline workspace controls', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('radio', { name: 'Student', exact: true }).check()
  await page.getByRole('button', { name: 'Load demo workspace' }).click()
  await expect(page).toHaveURL(/\/student$/)
  await page.locator('summary').filter({ hasText: /^Learning preferences$/ }).click()
  await page.getByRole('combobox', { name: 'Pace', exact: true }).selectOption('stepwise')
  await page.getByLabel('Enable non-essential personalisation').check()
  await page.getByRole('button', { name: 'Save preferences', exact: true }).click()
  await expect(page.getByText(/Preferences saved. Version/)).toBeVisible()
  await page.reload()
  await page.locator('summary').filter({ hasText: /^Learning preferences$/ }).click()
  await expect(page.getByRole('combobox', { name: 'Pace', exact: true })).toHaveValue('stepwise')
  await page.getByRole('button', { name: 'Continue learning', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Stepwise workspace guide' })).toBeVisible()
  await page.getByText('Change learning preferences', { exact: true }).click()
  await page.getByLabel('Enable non-essential personalisation').uncheck()
  await page.getByRole('button', { name: 'Save preferences', exact: true }).click()
  await expect(page.getByText(/Preferences saved. Version/)).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Stepwise workspace guide' })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Pace', exact: true })).toHaveValue('stepwise')
  await page.getByRole('button', { name: 'Reset and save defaults' }).click()
  await expect(page.getByText(/Preferences reset and saved/)).toBeVisible()
})
