import AxeBuilder from '@axe-core/playwright'
import { expect, test, type Page } from '@playwright/test'
import { apiUrl } from './urls'

async function signIn(page: Page, role: 'Student' | 'Educator', email: string, password: string) {
  await page.goto('/login')
  await page.getByRole('radio', { name: role, exact: true }).check()
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).not.toHaveURL(/\/login$/)
}

test('reviewed check preserves probe, help, revision, fresh evidence and human corrections', async ({ page, browser, request }, testInfo) => {
  test.setTimeout(120_000)
  page.setDefaultTimeout(15_000)
  const response = await request.post(`${apiUrl}/e2e/misconception-fixture`)
  expect(response.ok()).toBeTruthy()
  const fixture = await response.json()
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await signIn(page, 'Educator', fixture.educator_email, fixture.educator_password)
  await page.getByRole('link', { name: 'Misconception checks', exact: true }).click()
  await page.getByLabel('Saved learner work').selectOption(fixture.feedback_id)
  await page.getByRole('group', { name: 'Evidence behind the hypothesis' }).getByRole('checkbox').first().check()
  const hypothesis = 'Sampled counts may be confused with exact probabilities.'
  await page.getByLabel('Possible misconception', { exact: true }).fill(hypothesis)
  await page.getByLabel('Short check question').fill('Why might counts change between two runs?')
  await page.getByLabel('Alternate explanation', { exact: true }).fill('Sampling varies. Compare counts with the predicted distribution.')
  await page.getByLabel('Instructional help in the alternate explanation', { exact: true }).selectOption('2')
  await page.getByLabel('Fresh question', { exact: true }).fill('How would you compare two much larger sets of samples?')
  await page.getByLabel('Why this check will help').fill('The saved explanation leaves the role of sampling unclear.')
  await page.getByLabel('Source and teaching-content approval reason').fill('Synthetic course educator checked these questions and the explanation against the reviewed source.')
  await page.getByRole('checkbox', { name: 'Check question', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Fresh check', exact: true }).check()
  await page.getByRole('button', { name: 'Approve and open check' }).click()
  await expect(page).toHaveURL(/\/educator\/misconceptions\/[a-f0-9-]+$/)
  const identity = page.url().split('/').pop()!
  const learnerContext = await browser.newContext()
  const learner = await learnerContext.newPage()
  learner.setDefaultTimeout(15_000)
  learner.on('pageerror', error => errors.push(error.message))
  try {
    await signIn(learner, 'Student', fixture.student_email, fixture.student_password)
    await learner.getByRole('link', { name: 'Learning checks', exact: true }).click()
    await learner.getByRole('link', { name: hypothesis, exact: true }).click()
    await expect(learner.getByText('How would you compare two much larger sets of samples?')).toHaveCount(0)
    await expect(learner.getByRole('heading', { name: 'Alternate explanation' })).toHaveCount(0)
    const writeAnswer = async (answer: string) => {
      await learner.getByLabel('Your answer', { exact: true }).fill(answer)
      await learner.getByLabel('Explain your reasoning').fill('Observed proportions depend on sampling, while exact probabilities describe the state.')
      await learner.getByLabel('Instructional help used').selectOption('none')
    }
    await writeAnswer('Counts can vary between runs with the same circuit.')
    await learner.route(`**/misconceptions/${identity}/responses`, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Temporary save failure. Retry your saved draft.' }) }), { times: 1 })
    await learner.getByRole('button', { name: 'Save response', exact: true }).click()
    await expect(learner.getByRole('alert')).toContainText('Temporary save failure')
    await expect(learner.getByLabel('Your answer', { exact: true })).toHaveValue('Counts can vary between runs with the same circuit.')
    await learner.getByRole('button', { name: 'Save response', exact: true }).click()
    await expect(learner.getByRole('heading', { name: 'Alternate explanation', exact: true })).toBeVisible()
    await learner.reload()
    await expect(learner.getByText('Counts can vary between runs with the same circuit.', { exact: true })).toBeVisible()
    await writeAnswer('I now separate the sampled count from the underlying probability.')
    await learner.getByRole('button', { name: 'Save revision and start fresh check' }).click()
    await expect(learner.getByText('How would you compare two much larger sets of samples?')).toBeVisible()
    await expect(learner.getByText('Sampling varies. Compare counts with the predicted distribution.')).toHaveCount(0)
    await expect(learner.getByRole('heading', { name: 'Alternate explanation' })).toHaveCount(0)
    await writeAnswer('Larger samples usually produce proportions closer to the exact probability, while some variation remains.')
    await learner.getByRole('button', { name: 'Save response', exact: true }).click()
    await expect(learner.getByRole('heading', { name: 'Check question', exact: true })).toHaveCount(2)
    await expect(learner.getByText('Current state: Uncertain.', { exact: false })).toBeVisible()
    await page.reload()
    const recordReview = async (state: string, reason: string) => {
      await page.getByLabel('Check question evidence').selectOption('supports')
      await page.getByLabel('Fresh check evidence').selectOption('contradicts')
      await page.getByLabel('Reviewed state').selectOption(state)
      await page.getByLabel('Evidence and review reason').fill(reason)
      await page.getByLabel('Next teaching action and reason').fill('Compare counts from another approved circuit to check the distinction again.')
      await page.getByRole('button', { name: 'Record educator review' }).click()
    }
    await recordReview('UNCERTAIN', 'The fresh response challenges the hypothesis. Keep the earlier evidence for follow-up.')
    await expect(page.getByText('This unresolved check was sent to the human review queue.')).toBeVisible()
    await recordReview('CORRECTED', 'After reviewing the unaided fresh explanation, the original misconception is corrected in this cycle.')
    await expect(page.getByRole('heading', { name: 'Review 2: Corrected' })).toBeVisible()
    await learner.getByRole('button', { name: 'Refresh this check' }).click()
    await expect(learner.getByRole('heading', { name: 'Review 1: Uncertain' })).toBeVisible()
    await expect(learner.getByRole('heading', { name: 'Review 2: Corrected' })).toBeVisible()
    expect((await new AxeBuilder({ page: learner }).include('main').withTags(['wcag2a', 'wcag2aa']).analyze()).violations).toEqual([])
    const screenshot = testInfo.outputPath('misconception-history.png')
    await learner.screenshot({ path: screenshot, fullPage: true })
    await testInfo.attach('misconception-history', { path: screenshot, contentType: 'image/png' })
    await learner.getByRole('link', { name: 'Learning progress', exact: true }).click()
    await learner.getByLabel('Course', { exact: true }).selectOption(fixture.course_id)
    await expect(learner.getByRole('heading', { name: 'Observed work', exact: true })).toBeVisible()
    await learner.getByText('Uncertain learning estimates', { exact: true }).click()
    await expect(learner.getByRole('cell', { name: 'possible misconception', exact: true }).first()).toBeVisible()
    await expect(learner.getByRole('cell', { name: 'uncertain', exact: true }).first()).toBeVisible()
    await learner.getByRole('link', { name: /supports:/ }).first().click()
    await expect(learner.getByRole('heading', { name: 'Saved learning observation' })).toBeVisible()
    await learner.goBack()
    await learner.getByText('Inspect recent observations', { exact: true }).click()
    await learner.getByRole('listitem').filter({ hasText: /^response,/ }).getByRole('link', { name: 'Inspect this observation' }).click()
    await expect(learner.getByRole('heading', { name: 'Answer', exact: true })).toBeVisible()
    await learner.goBack()
    await expect(learner.getByRole('heading', { name: 'Observed work' })).toBeVisible()

    await expect(learner.getByText(/Result not released:/).first()).toBeVisible()
    await expect(learner.getByRole('link', { name: /Inspect check 1/ })).toHaveAttribute('href', `/student/misconceptions/${identity}`)
    expect((await new AxeBuilder({ page: learner }).include('main').withTags(['wcag2a', 'wcag2aa']).analyze()).violations).toEqual([])
    const progressScreenshot = testInfo.outputPath('learning-progress.png')
    await learner.screenshot({ path: progressScreenshot, fullPage: true })
    await testInfo.attach('learning-progress', { path: progressScreenshot, contentType: 'image/png' })
    await learner.getByRole('link', { name: 'Inspect estimate and correction history' }).click()
    await expect(learner.getByRole('heading', { name: 'Ordered history', exact: true })).toBeVisible()
    await expect(learner.getByLabel('Course ID')).toHaveValue(fixture.course_id)
    await page.goto(`/educator/analytics?course=${fixture.course_id}`)
    await expect(page.getByRole('heading', { name: 'Cohort learning progress' })).toBeVisible()
    await page.getByRole('button', { name: /^Focus on / }).click()
    await expect(page.getByRole('button', { name: 'Show the whole cohort' })).toBeVisible()
    await page.getByRole('link', { name: 'Inspect estimate and correction history' }).click()
    await expect(page.getByRole('heading', { name: 'Ordered history', exact: true })).toBeVisible()
    expect(errors).toEqual([])
  } finally { await learnerContext.close() }
})
