import { chromium, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const scratch = resolve('../backend/.tmp-task15', process.env.TASK15_BROWSER_RUN ?? 'browser')
const fixture = JSON.parse(readFileSync(resolve(scratch, 'context.json'), 'utf8'))
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const context = await browser.newContext({ viewport: { width: 1365, height: 900 } })
const page = await context.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
try {
  await page.goto('http://localhost:5255')
  await page.getByRole('radio', { name: 'Educator', exact: true }).check()
  await page.getByLabel('Email address').fill(fixture.assessor_email)
  await page.getByLabel('Password', { exact: true }).fill('definition-test-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.waitForURL('**/educator')
  await page.goto('http://localhost:5255/assessor/review')
  const inspect = page.getByRole('button', { name: new RegExp(`Inspect attempt ${fixture.attempt_id}`) })
  await inspect.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByText('Half zero, half one', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Fresh application', { exact: true }).first()).toBeVisible()
  await page.getByText(`Inspect earlier response ${fixture.original_response_id}`, { exact: true }).click()
  await expect(page.getByRole('region', { name: 'Earlier immutable responses' })).toBeVisible()
  await page.screenshot({ path: resolve(scratch, 'frozen-evidence.png'), fullPage: true })
  const decisions = page.locator('select[id^="decision-"]')
  for (let i = 0; i < await decisions.count(); i++) await decisions.nth(i).selectOption('MET')
  const reasons = page.locator('textarea[id^="reason-"]')
  for (let i = 0; i < await reasons.count(); i++) await reasons.nth(i).fill('The supported explanation and fresh transfer response show the approved criterion.')
  const checks = page.getByRole('checkbox', { name: /Whole immutable learner response/ })
  for (let i = 0; i < await checks.count(); i++) await checks.nth(i).check()
  await page.getByLabel('Formal confirmation reason').fill('I inspected the complete frozen multipart response and applied its approved standard.')
  const axe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()
  if (axe.violations.length) throw new Error(JSON.stringify(axe.violations.map(({ id, nodes }) => ({ id, nodes: nodes.map(node => node.target) }))))
  const confirm = page.getByRole('button', { name: 'Apply frozen pass rule and confirm result' })
  await confirm.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByText('Formal result PASS confirmed. Your criterion decisions and reasons are saved.')).toBeVisible()
  await expect(page.getByText('1 review record loaded.', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Criterion decisions', exact: true })).toBeVisible()
  await page.screenshot({ path: resolve(scratch, 'confirmed-result.png'), fullPage: true })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Assessment review queue' })).toBeVisible()
  await expect(page.getByText('1 review record loaded.', { exact: true })).toBeVisible()
  await expect(page.getByText(/Evaluator: human:/)).toBeVisible()
  await expect(page.getByRole('button', { name: new RegExp(`Inspect attempt ${fixture.attempt_id}`) })).toHaveCount(0)
  if (errors.length) throw new Error(errors.join('\n'))
  writeFileSync(resolve(scratch, 'result.json'), JSON.stringify({ passed: true, channel: 'chrome-stable', axeViolations: axe.violations.length, keyboardInspectAndConfirm: true, fixture, pageErrors: errors }, null, 2))
  console.log('PASS: real unresolved job, assessor login, frozen multipart evidence and history, criterion entry, audited confirmation, reload, keyboard controls, and Axe')
} finally { await browser.close() }
