import { chromium, expect } from '@playwright/test'
import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { resolve } from 'node:path'
import AxeBuilder from '@axe-core/playwright'
const backend = resolve('../backend')
const scratch = resolve(backend, '.tmp-task14', process.env.TASK14_BROWSER_RUN ?? 'browser')
const fixture = JSON.parse(readFileSync(resolve(scratch, 'context.json'), 'utf8'))
const typedEpisode = fixture.task_type !== 'quantum_circuit'
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const context = await browser.newContext({ viewport: { width: 1365, height: 900 } })
const page = await context.newPage()
const requests = []
page.on('request', request => {
  if (/\/(start|draft|submissions|checkpoints|transfer|simulate)$/.test(request.url()) && request.method() !== 'GET') requests.push({ path: new URL(request.url()).pathname, method: request.method(), body: request.postDataJSON() })
})
try {
  await page.goto('http://localhost:5244')
  await page.getByLabel('Email address').fill(fixture.student_email)
  await page.getByLabel('Password', { exact: true }).fill('quantumlearn-demo')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.waitForURL('**/student')
  await page.goto(`http://localhost:5244/student/tasks/${fixture.task_id}`)
  await expect(page.getByRole('heading', { name: 'Learning episode' })).toBeVisible()
  await expect(page.getByText('SYNTHETIC PRIVATE fresh Hadamard application')).toHaveCount(0)
  await expect(page.getByText('Consider how H changes the input state.', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Request conceptual hint 1', exact: true }).click()
  await expect(page.getByLabel('Requested conceptual hint')).toHaveText('Consider how H changes the input state.')
  await page.reload()
  await page.getByText('Support request history', { exact: true }).click()
  await expect(page.getByText(/Conceptual hint request 1, supported response/)).toBeVisible()
  await page.getByText('Support request history', { exact: true }).click()
  if (!typedEpisode) {
    await page.getByRole('button', { name: 'Add H gate', exact: true }).focus()
    await page.keyboard.press('Enter')
  }
  await page.getByLabel('Your prediction before results').fill('  Half zero and half one\n')
  await page.getByLabel('Your reasoning', { exact: true }).fill('  H creates equal amplitudes\n')
  await page.getByRole('button', { name: 'Record prediction for this input', exact: true }).click()
  await expect(page.getByText('Prediction and current input saved before results.')).toBeVisible()
  if (!typedEpisode) {
    execFileSync(process.env.TASK14_PYTHON, ['tests/task14_browser_server.py', 'fail-next'], { cwd: backend, env: { ...process.env, PYTHONPATH: backend }, windowsHide: true })
    await page.getByRole('button', { name: 'Run 1,024 shots' }).click()
    await expect(page.getByText(/Simulation reached its time limit/)).toBeVisible()
    await page.screenshot({ path: resolve(scratch, 'controlled-timeout.png'), fullPage: true })
  }
  await page.reload()
  await expect(page.getByLabel('Your prediction before results')).toHaveValue('  Half zero and half one\n')
  await expect(page.getByLabel('Your reasoning', { exact: true })).toHaveValue('  H creates equal amplitudes\n')
  for (let index = 0; index < 20; index += 1) {
    await page.getByRole('button', { name: 'Write a new prediction', exact: true }).click()
    await page.getByLabel('Your prediction before results').fill(`  Updated prediction ${index + 1}: half each\n`)
    await page.getByRole('button', { name: 'Record prediction for this input', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Write a new prediction', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Save draft', exact: true })).toBeEnabled()
  }
  await page.getByText('View saved predictions and inputs', { exact: true }).click()
  await page.getByRole('button', { name: 'Load earlier predictions', exact: true }).click()
  await expect(page.getByText('Half zero and half one', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Load earlier predictions', exact: true })).toHaveCount(0)
  await page.getByText('View saved predictions and inputs', { exact: true }).click()
  if (!typedEpisode) {
    await page.getByRole('button', { name: 'Run 1,024 shots' }).click()
    await expect(page.getByText('Simulation completed and saved with 1,024 shots.')).toBeVisible({ timeout: 30000 })
  }
  await page.getByLabel('Explain the result', { exact: true }).fill('  Each outcome has probability one half\n')
  await page.getByLabel('Your reflection', { exact: true }).fill('  The technical fault kept my work\n')
  await page.getByRole('button', { name: 'Start unaided fresh application' }).click()
  await expect(page.getByText('SYNTHETIC PRIVATE fresh Hadamard application')).toBeVisible()
  await expect(page.getByText('NEVER REVEAL solution')).toHaveCount(0)
  await expect(page.getByText('Conceptual hints, use as often as needed')).toHaveCount(0)
  await expect(page.getByLabel('Requested conceptual hint')).toHaveCount(0)
  await page.getByRole('button', { name: 'I used access support 1', exact: true }).click()
  await expect(page.getByText('Access support noted. It does not lower your result.')).toBeVisible()
  await page.getByLabel('Fresh application response', { exact: true }).fill('  Apply H to a fresh input\n')
  await page.getByLabel('Fresh application code', { exact: true }).fill('  circuit.h(0)\n')
  await page.getByRole('button', { name: 'Add fresh H gate' }).click()
  await page.getByLabel('Fresh application reasoning', { exact: true }).fill('  Fresh reasoning\n')
  await page.getByLabel('Fresh application prediction', { exact: true }).fill('  Half each for the fresh circuit\n')
  await page.getByRole('button', { name: 'Record fresh prediction', exact: true }).click()
  await page.getByRole('button', { name: 'Run fresh circuit', exact: true }).click()
  await expect(page.getByText('Fresh application simulation saved. Results are shown in this workspace.')).toBeVisible({ timeout: 30000 })
  await expect(page.getByRole('table', { name: 'Exact probabilities and sampled frequencies' })).toBeVisible()
  await expect(page.getByText('50.00%', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  await expect(page.getByText('Draft saved.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Fresh application code', { exact: true })).toHaveValue('  circuit.h(0)\n')
  await page.getByRole('button', { name: 'Submit activity', exact: true }).click()
  await expect(page.getByText('Assessment response saved', { exact: true }).first()).toBeVisible({ timeout: 30000 })
  await expect(page.getByRole('button', { name: 'Save draft', exact: true })).toBeEnabled()
  await page.getByLabel('Revise an earlier response').selectOption({ index: 1 })
  await page.getByLabel('Reason for your revision').fill('  More precise explanation after reviewing my work\n')
  await page.getByLabel('Your reflection', { exact: true }).fill('  Reflection preserved after submission\n')
  await page.getByRole('button', { name: 'Submit activity', exact: true }).click()
  await expect(page.getByText('2 attempts', { exact: true })).toBeVisible({ timeout: 30000 })
  await expect(page.getByRole('button', { name: 'Save draft', exact: true })).toBeEnabled()
  await page.screenshot({ path: resolve(scratch, 'submitted-episode.png'), fullPage: true })
  const accessibility = await new AxeBuilder({ page }).analyze()
  const serious = accessibility.violations.filter(item => ['serious', 'critical'].includes(item.impact))
  writeFileSync(resolve(scratch, 'result.json'), JSON.stringify({ passed: serious.length === 0, requests, accessibility: serious }, null, 2))
  if (serious.length) throw new Error(`Accessibility violations: ${serious.map(item => item.id).join(', ')}`)
  console.log(`PASS: ${fixture.task_type}, durable support request/reload, paged predictions, private transfer, visible simulation, submission/revision, axe${typedEpisode ? '' : ', controlled timeout preservation'}`)
} finally { await browser.close() }
